services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'devopsDB'
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '4000:4000'
    expose:
      # Opens port 3306 on the container
      - '4000'
      # Where our data will be persisted
  backend:
    image: "72821/spring-app.jar"
    ports:
      - "8080:8000"
    depends_on:
      - db
  frontend:
    image: "72821/devops-test-angular"
    ports: 
      - 3000:80