services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'devopsDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'my-secret-pw'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '4000:3306'
    expose:
      # Opens port 3306 on the container
      - '4000'
      # Where our data will be persisted
  backend:
    image: "72821/spring-app.jar"
    ports:
      - "8080:8000"
  frontend:
    image: "72821/devops-test-angular"
    ports: 
      - 3000:80