services:
  web:
    image: 72821/nginx-proxy
    ports: 
      - "80:80"
    depends_on:
      - backend
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'devopsDB'
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  backend:
    image: "72821/spring-app.jar"
    ports:
      - "8080:8000"
    depends_on:
      - db
  frontend:
    image: "72821/devops-test-angular"
    ports: 
      - 3000:80